__default__:
  jobname: "default"
  mem: "32G"
  cpus: 10
  time: "15:00:00"
  partition: "workq"

## pairing ##
split_fastq:
    jobname: "split_fastq"
    mem: "1G"
pairing:
    jobname: "pairing"
    mem: "32G"
    cpus: 100
    time: "96:00:00"
## alignment sorting ##
alifilt:
    jobname: "alifilt"
    mem: "32G"
    time: "15:00:00"
## demultiplex ##
demultiplex:
    jobname: "demultiplex"
    mem: "32G"
    cpus: 100
    time: "96:00:00"
## basic filtration ##
basicfilt:
    jobname: "basicfilt"
    time: "15:00:00"
## dereplication ##
derepl:
    jobname: "derepl"
    mem: "32G"
    cpus: 40
    time: "24:00:00"    
## obiclean ##
#obiclean_07:
#    jobname: "obiclean_07"
#    mem: "32G"
#    time: "168:00:00"
#    partition: "unlimitq"
## otu clustering ##
otu_clust:
    jobname: "otu_clust"
    mem: "64G"
    time: "96:00:00"
## merge clustering ##
merge_clust:
    jobname: "merge_clust"
    mem: "32G"
    time: "96:00:00"
## format output ##
tab_format:
    jobname: "tab_format"
    mem: "32G"
    time: "96:00:00"
## sequence tracking ##
seq_tracking:
    jobname: "seq_tracking"
    mem: "32G"
    time: "96:00:00"
## taxonomy assignments ##
taxassign:
    jobname: "taxassign"
    cpus: 40
    mem: "256G"
    time: "96:00:00"
## Benchmark ##
benchmark:
    jobname: "benchmark"
    mem: "2G"
    time: "02:00:00"

